// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountUserSessions(ctx context.Context, userID pgtype.UUID) (int64, error)
	// Audit logs
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	// Sessions
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Users
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error
	DeleteUserSessions(ctx context.Context, userID pgtype.UUID) error
	GetOldestUserSession(ctx context.Context, userID pgtype.UUID) (Session, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByEmailVerificationTokenHash(ctx context.Context, emailVerificationTokenHash string) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	IncrementFailedLoginAttempts(ctx context.Context, id pgtype.UUID) (User, error)
	LockUser(ctx context.Context, arg LockUserParams) error
	PurgeAuditLogsBefore(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	ResetFailedLoginAttempts(ctx context.Context, id pgtype.UUID) error
	SetEmailVerificationToken(ctx context.Context, arg SetEmailVerificationTokenParams) error
	UnlockUser(ctx context.Context, id pgtype.UUID) error
	UpdateSessionLastActive(ctx context.Context, id pgtype.UUID) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertUserByGoogleID(ctx context.Context, arg UpsertUserByGoogleIDParams) (User, error)
	VerifyUserEmail(ctx context.Context, id pgtype.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
